apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database-deployment
  labels:
    name: user-database-deployment
    app: event-driven-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-database
      app: event-driven-ms
  template:
    metadata:
      name: user-database
      labels:
        name: user-database
        app: event-driven-ms
    spec:
      containers:
        - name: user-database
          image: postgres:14.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "user"
---
apiVersion: v1
kind: Service
metadata:
  name: user-database # host name for service
  labels:
    name: user-database-service
    app: event-driven-ms
spec:
  type: ClusterIP
  selector:
    name: user-database
    app: event-driven-ms
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-endpoint
  labels:
    name: user-database-endpoint
    app: event-driven-ms
spec:
  type: LoadBalancer
  selector:
    name: user-database
    app: event-driven-ms
  ports:
    - port: 5432
      name: client
      targetPort: 5432
      nodePort: 30089