apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-database-deployment
  labels:
    name: product-database-deployment
    app: event-driven-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product-database
      app: event-driven-ms
  template:
    metadata:
      name: product-database
      labels:
        name: product-database
        app: event-driven-ms
    spec:
      containers:
        - name: product-database
          image: postgres:14.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "product"
---
apiVersion: v1
kind: Service
metadata:
  name: product-database # host name for service
  labels:
    name: product-database-service
    app: event-driven-ms
spec:
  type: ClusterIP
  selector:
    name: product-database
    app: event-driven-ms
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: product-database-endpoint
  labels:
    name: product-database-endpoint
    app: event-driven-ms
spec:
  type: LoadBalancer
  selector:
    name: product-database
    app: event-driven-ms
  ports:
    - port: 5432
      name: client
      targetPort: 5432
      nodePort: 30083