apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-master-deployment
  labels:
    name: eureka-master-deployment
    app: event-driven-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eureka-master
      app: event-driven-ms
  template:
    metadata:
      name: eureka-master
      labels:
        name: eureka-master
        app: event-driven-ms
    spec:
      containers:
        - name: eureka-master
          image: liem18112000/euraka-discovery-server:1.0
          ports:
            - containerPort: 8761
          env:
            - name: eureka.client.service-url.defaultZone
              value: "http://eureka-master:8761/eureka"
            - name: ACTIVE_PROFILE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-master
  labels:
    name: eureka-master-service
    app: event-driven-ms
spec:
  type: ClusterIP
  selector:
    name: eureka-master
    app: event-driven-ms
  ports:
    - port: 8761
      targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-master-endpoint
  labels:
    name: eureka-master-endpoint
    app: event-driven-ms
spec:
  type: LoadBalancer
  selector:
    name: eureka-master
    app: event-driven-ms
  ports:
    - port: 8761
      name: ui
      targetPort: 8761
      nodePort: 30081