server:
  port: ${SERVER_PORT:5000}
  forward-headers-strategy: framework
spring:
  profiles:
    active: ${ACTIVE_PROFILES:dev}
  application:
    name: ${APPLICATION_NAME:gateway-service}
#  r2dbc:
#    url: r2dbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:13306}/${DATABASE_NAME:gateway}?serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: ${DATABASE_USER:root}
#    password: ${DATABASE_PASS:root}
#    properties:
#      sslMode: DISABLED
#    pool:
#      enabled: true
#      initial-size: 22
#      max-size: 30
#      max-idle-time: 5m
#      validation-query: SELECT 1
#  liquibase:
#    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:13306}/${DATABASE_NAME:gateway}?serverTimezone=UTC&useLegacyDatetimeCode=false
#    user: ${DATABASE_USER:root}
#    password: ${DATABASE_PASS:root}
#    enabled: ${LIQUIBASE_ENABLED:true}
#    change-log: ${LIQUIBASE_CHANGELOG:classpath:/db/changelog-master.xml}
#    contexts: ${LIQUIBASE_CONTEXTS:default}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      default-zone: http://eureka-master:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
management:
  endpoints:
    web:
      exposure:
        include: "*"