spring:
  profiles:
    active: ${ACTIVE_PROFILE:default}
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://eureka-master:8761/eureka
  instance:
    hostname: eureka-master
    appname: eureka-cluster
  environment: ${EUREKA_ENVIRONMENT:develop}
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eureka-peer-1
    appname: eureka-cluster
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-master:8761/eureka,http://eureka-peer-2:8763/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8762

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer-2
    appname: eureka-cluster
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-master:8761/eureka,http://eureka-peer-1:8762/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8763