server:
  port: ${SERVER_PORT:8082}
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
  servlet:
    context-path: /user
logging:
  file:
    path: ${LOG_PATH:logs}
    name: ${logging.file.path}/${LOG_FILE:application}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE:application}.%d{dd-MM-yyyy}.%i.log
      max-file-size: ${LOG_MAX_FILE_SIZE:10MB}
      max-history: ${LOG_MAX_HISTORY:20}
  pattern:
    console: "%green(%d{${ISO8601}}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
  level:
    org.axonframework: INFO
    com.liem.ms: TRACE
    org.springframework: ERROR
spring:
  profiles:
    active: ${ACTIVE_PROFILES:dev}
  application:
    name: ${APPLICATION_NAME:user-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:25432}/${DATABASE_NAME:order}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:/db/changelog-master.xml}
    contexts: ${LIQUIBASE_CONTEXTS:default}
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      default-zone: http://eureka-master:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8124}
  eventhandling:
    processors:
      user-group:
        mode: subscribing