server:
  port: ${SERVER_PORT:8083}
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
  servlet:
    context-path: /user
spring:
  profiles:
    active: ${ACTIVE_PROFILES:dev}
  application:
    name: ${APPLICATION_NAME:user-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:45432}/${DATABASE_NAME:user}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:/db/changelog-master.xml}
    contexts: ${LIQUIBASE_CONTEXTS:default}
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      default-zone: http://eureka-master:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
axon:
  axonserver:
    servers: ${AXON_SERVER_HOST:localhost}:${AXON_SERVER_PORT:8124}
  eventhandling:
    processors:
      user-group:
        mode: subscribing