server:
  port: ${SERVER_PORT:8084}
  forward-headers-strategy: framework
logging:
  file:
    path: ${LOG_PATH:logs}
    name: ${logging.file.path}/${LOG_FILE:application}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE:application}.%d{dd-MM-yyyy}.%i.log
      max-file-size: ${LOG_MAX_FILE_SIZE:10MB}
      max-history: ${LOG_MAX_HISTORY:20}
  pattern:
    console: "%green(%d{${ISO8601}}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
resilience4j:
  circuitbreaker:
    instances:
      global:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 3
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 3s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      global:
        register-health-indicator: true
        timeoutDuration: 10s
        cancelRunningFuture: true
  retry:
    instances:
      global:
        register-health-indicator: true
        maxAttempts: 5
        waitDuration: 30s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  bulkhead:
    instances:
      global:
        maxWaitDuration: 1s
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    instances:
      global:
        maxThreadPoolSize: 10
        coreThreadPoolSize: 3
        queueCapacity: 5
spring:
  profiles:
    active: ${ACTIVE_PROFILES:dev}
  application:
    name: ${APPLICATION_NAME:security-service}
    server: ${APPLICATION_SERVER:localhost}
    endpoint: ${spring.application.server}:${server.port}
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration: ${JWT_EXPIRATION:3600s}
    cache-duration: ${JWT_CACHE_DURATION:1200s}
    white-list: /,/explorer/**,/auth/ping/no-auth,/webjars/**,/v3/api-docs,/v3/api-docs.*,/v3/api-docs/**,/swagger-ui.*,/swagger-ui/**,/actuator/health,/auth/access-token,/auth/register
  refresh-token:
    secret: ${REFRESH_TOKEN_SECRET:refresh_secret}
    expiration: ${REFRESH_TOKEN_EXPIRATION:30d}
    cache-duration: ${REFRESH_TOKEN_CACHE_DURATION:12h}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:25672}
    exchange: ${RABBITMQ_EXCHANGE:service.security.exchange}
    queue: ${RABBITMQ_QUEUE:service.security.queue}
    routing-key: ${RABBITMQ_ROUTING_KEY:service.security.routing-key}
    durable: ${RABBITMQ_DURABLE:true}
    virtual-host: ${RABBITMQ_VHOST:/}
    template:
      reply-timeout: ${RABBITMQ_REPLY_TIMEOUT:15s}
    listener:
      simple:
        retry:
          max-attempts: ${RABBITMQ_RETRY_MAX_ATTEMPS:3}
          enabled: ${RABBITMQ_RETRY_ENABLED:true}
          max-interval: ${RABBITMQ_RETRY_MAX_INTERVAL:15s}
          initial-interval: ${RABBITMQ_RETRY_INITIAL_INTERVAL:3s}
    publisher-confirm-type: correlated
    publisher-returns: true
    cache:
      connection:
        mode: channel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:13306}/${DATABASE_NAME:security}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:root}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGELOG:classpath:/db/changelog-master.xml}
    contexts: ${LIQUIBASE_CONTEXTS:default}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:16379}
    connect-timeout: 30s
    timeout: 10s
    cache-duration:
      users: ${USERS_CACHE_DURATION:600s}
      roles: ${ROLES_CACHE_DURATION:600s}
      resources: ${RESOURCES_CACHE_DURATION:1200s}
    password: ${REDIS_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      default-zone: http://eureka-master:8761/eureka
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true