version: '3.8'
services:
#  gateway-database:
#    image: mysql:5.7
#    container_name: gateway-database
#    restart: always
#    networks:
#      - microservice
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$GATEWAY_DATABASE_PASS
#      - MYSQL_DATABASE=$GATEWAY_DATABASE_NAME
#    ports:
#      - $GATEWAY_DATABASE_SERVER_PORT:$GATEWAY_DATABASE_DOCKER_PORT
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "38081:8081"

  product-database:
    container_name: product-database
    image: postgres:14.1-alpine
    env_file: ./.env
    networks:
      - microservice
    ports:
      - $PRODUCT_DATABASE_SERVER_PORT:$PRODUCT_DATABASE_DOCKER_PORT
    environment:
      - POSTGRES_USER=$PRODUCT_DATABASE_USER
      - POSTGRES_DB=$PRODUCT_DATABASE_NAME
      - POSTGRES_PASSWORD=$PRODUCT_DATABASE_PASS

  order-database:
    container_name: order-database
    image: postgres:14.1-alpine
    env_file: ./.env
    networks:
      - microservice
    ports:
      - $ORDER_DATABASE_SERVER_PORT:$ORDER_DATABASE_DOCKER_PORT
    environment:
      - POSTGRES_USER=$ORDER_DATABASE_USER
      - POSTGRES_DB=$ORDER_DATABASE_NAME
      - POSTGRES_PASSWORD=$ORDER_DATABASE_PASS

  payment-database:
    container_name: payment-database
    image: postgres:14.1-alpine
    env_file: ./.env
    networks:
      - microservice
    ports:
      - $PAYMENT_DATABASE_SERVER_PORT:$PAYMENT_DATABASE_DOCKER_PORT
    environment:
      - POSTGRES_USER=$PAYMENT_DATABASE_USER
      - POSTGRES_DB=$PAYMENT_DATABASE_NAME
      - POSTGRES_PASSWORD=$PAYMENT_DATABASE_PASS

  axon-server:
    container_name: axon-server
    image: axoniq/axonserver:latest-dev
    hostname: axon-server
    env_file: ./.env
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-config:/axonserver/config:ro
    ports:
      - $AXON_UI_SERVER_PORT:$AXON_UI_DOCKER_PORT
      - $AXON_GRPC_SERVER_PORT:$AXON_GRPC_DOCKER_PORT
    networks:
      - microservice

  eureka-master:
    container_name: eureka-master
    hostname: eureka-master
    image: liem18112000/euraka-discovery-server:1.0
    ports:
      - "8761:8761"
    networks:
      - microservice
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-master:8761/eureka
      - ACTIVE_PROFILE=default

  axon-product-service:
    container_name: axon-product-service
    image: liem18112000/axon-product-service:1.1
    depends_on:
      - product-database
      - axon-server
      - eureka-master
    ports:
      - $PRODUCT_SERVICE_SERVER_PORT:$PRODUCT_SERVICE_DOCKER_PORT
    networks:
      - microservice
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-master:8761/eureka
      - SERVER_PORT=$PRODUCT_SERVICE_DOCKER_PORT
      - DATABASE_HOST=$PRODUCT_DATABASE_HOST
      - DATABASE_PORT=$PRODUCT_DATABASE_DOCKER_PORT
      - DATABASE_PASS=$PRODUCT_DATABASE_PASS
      - DATABASE_USER=$PRODUCT_DATABASE_USER
      - AXON_SERVER_HOST=$AXON_SERVER_HOST
      - AXON_SERVER_PORT=$AXON_GRPC_DOCKER_PORT

  axon-order-service:
    container_name: axon-order-service
    image: liem18112000/axon-product-service:1.1
    depends_on:
      - order-database
      - axon-server
      - eureka-master
    ports:
      - $ORDER_SERVICE_SERVER_PORT:$ORDER_SERVICE_DOCKER_PORT
    networks:
      - microservice
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-master:8761/eureka
      - SERVER_PORT=$ORDER_SERVICE_DOCKER_PORT
      - DATABASE_HOST=$ORDER_DATABASE_HOST
      - DATABASE_PORT=$ORDER_DATABASE_DOCKER_PORT
      - DATABASE_PASS=$ORDER_DATABASE_PASS
      - DATABASE_USER=$ORDER_DATABASE_USER
      - AXON_SERVER_HOST=$AXON_SERVER_HOST
      - AXON_SERVER_PORT=$AXON_GRPC_DOCKER_PORT

networks:
  microservice:
    driver: bridge
volumes:
  axonserver-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/data
  axonserver-events:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/events
  axonserver-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/config
  nexus-data: